var year2008 =[
["",
"Oxidation of Guanine in G, GG, and GGG Sequence Contexts by Aromatic Pyrenyl Radical Cations and Carbonate Radical Anions: Relationship between Kinetics and Distribution of Alkali-Labile Lesions. J Phys Chem B. 2008 Feb 14;112(6):1834-44 (2008).",
"Lee YA, Durandin A, Dedon PC, Geacintov NE, Shafirovich V"],

["",
"Pathways of arachidonic Acid peroxyl radical reactions and product formation with Guanine radicals. Chem Res Toxicol. 21(2):358-73(2008).",
"Crean C, Geacintov NE, Shafirovich V."],

["",
"Oxidation of single-stranded oligonucleotides by carbonate radical anions: generating intrastrand cross-links between guanine and thymine bases separated by cytosines. Nucleic Acids Res. 36(3):742-55 (2008).",
"Crean C, Uvaydov Y, Geacintov NE, Shafirovich V. "],

["",
"DNA adduct structure-function relationships: comparing solution with polymerase structures. Chem Res Toxicol. 21(1):45-52 (2008). Review",
"Broyde S, Wang L, Zhang L, Rechkoblit O, Geacintov NE, Patel DJ."],

["",
"Nucleotide Selectivity Opposite a Benzo[a]pyrene-Derived N(2)-dG Adduct in a Y-Family DNA Polymerase: A 5'-Slippage Mechanism. Biochemistry. 47(9):2701-9 (2008).",
"Xu P, Oum L, Geacintov NE, Broyde S."],

["",
"Oxidation of guanine in G, GG, and GGG sequence contexts by aromatic pyrenyl radical cations and carbonate radical anions: relationship between kinetics and distribution of alkali-labile lesions. J Phys Chem B. 2008 Feb 14;112:1834-44.",
"Lee YA, Durandin A, Dedon PC, Geacintov NE, Shafirovich V. "],

["",
"Conformational Properties of Equilenin-DNA Adducts: Stereoisomer and Base Effects. Chem Res Toxicol. (2008) 21: 1064-73.",
"Ding S, Shapiro R, Cai Y, Geacintov NE, Broyde S."],

["",
"Determination of absolute configurations of 4-hydroxyequilenin-cytosine and -adenine adducts by optical rotatory dispersion, electronic circular dichroism, density functional theory calculations, and mass spectrometry. Chem. Res. Toxicol. (2008) 21: 1739-48.",
"Ding, S., Wang, Y., Kolbanovskiy, A., Durandin, A., Bolton, J.L., van Breemen, R.B., Broyde, S., and Geacintov, N.E. "],

["",
"Analysis of strand transfer and template switching mechanisms of DNA gap repair by homologous recombination in Escherichia coli: predominance of strand transfer. J Mol Biol. (2008) 381:803-9. PMID: 18585391",
"Izhar L, Goldsmith M, Dahan R, Geacintov N, Lloyd RG, Livneh Z. "],

["",
"Lesion processing: high-fidelity versus lesion-bypass DNA polymerases. Trends Biochem Sci. (2008) 33:209-19 (Review) . PMID: 18407502",
"Broyde S, Wang L, Rechkoblit O, Geacintov NE, Patel DJ."],

["",
"Oxidation of guanine by carbonate radicals derived from photolysis of carbonatotetramminecobalt(III) complexes and the pH dependence of intrastrand DNA cross-links mediated by guanine radical reactions. Chembiochem (2008) 9:1985-91. PMID: 18655084",
"Crean C, Lee YA, Yun BH, Geacintov NE, Shafirovich V. "],

["",
"Reduced efficiency and increased mutagenicity of translesion DNA synthesis across a TT cyclobutane pyrimidine dimer, but not a TT 6-4 photoproduct, in human cells lacking DNA polymerase eta. DNA Repair (Amst). (2008) 7(10):1636-46. PMID: 18634905",
"Hendel A, Ziv O, Gueranger Q, Geacintov N, Livneh Z. "],

["",
"Transcription of DNA containing the 5-guanidino-4-nitroimidazole lesion by human RNA polymerase II and bacteriophage T7 RNA polymerase. DNA Repair (Amst). (2008) 7:1276-88. PMID: 18555749",
"Dimitri A, Jia L, Shafirovich V, Geacintov NE, Broyde S, Scicchitano DA."],

["",
"A cigarette, an aromatic...and a cancer. Med Sci (Paris). 2008 Mar;24(3):233-4. French. PMID: 18334163",
"Mocquet V, Egly JM, Geacintov N."],

["",
"Intrastrand G-U cross-links generated by the oxidation of guanine in 5’-d(GCU) and 5’-r(GCU). Free Radic Biol Med. 45(8):1125-34 (2008). PMID: 18692567",
"Crean C, Geacintov NE, Shafirovich V. "],

["",
"The N-clasp of human DNA polymerase kappa promotes blockage or error- free adenine- or guanine-benzo[a]pyrenyl lesions. Nucleic Acids Res. 36(20):6571-84 (2008). PMID: 18931375.",
"Jia L, Geacintov NE, Broyde S."],

["",
"DNA sequence context as a determinant of the quantity and chemistry of guanine oxidation produced by hydroxyl radicals and one-electron oxidants. J Biol Chem. 283(51):35569-78 (2008). PMID: 18948263.",
"Margolin Y, Shafirovich V, Geacintov NE, DeMott MS, Dedon PC."],

["",
"Lesion Specificity in the Base Excision Repair Enzyme hNeil1: Modeling and Dynamics Studies. Biochemistry 46(18):5305-14 (2007). Subach OM, Maltseva DV, Shastry A, Kolbanovskiy A, Klimasauskas S, Geacintov NE, Gromova ES. The stereochemistry of benzo[a]pyrene-2'-deoxyguanosine adducts affects DNA methylation by SssI and HhaI DNA methyltransferases. FEBS J. 274(8):2121-34 (2007).",
"Jia, L, Shafirovich V, Geacintov NE, Broyde S."],

["",
"Mechanisms of Oxidation of Guanine in DNA by Carbonate Radical Anion, a Decomposition Product of Nitrosoperoxycarbonate. Chemistry (Eur. J.) 13 (16):4571-81 (2007).",
"Lee YA, Yun BH, Kim SK, Margolin Y, Dedon PC, Geacintov NE, Shafirovich V. "],

["",
"Exocyclic amino groups of flanking guanines govern sequence-dependent adduct conformations and local structural distortions for minor groove-aligned benzo[a]pyrenyl-guanine lesions in a GG mutation hotspot context. Nucleic Acids Res. 35(5):1555-68 (2007).",
"Rodriguez FA, Cai Y, Lin C, Tang Y, Kolbanovskiy A, Amin S, Patel DJ, Broyde S, Geacintov NE."],

["",
"4-hydroxyequilenin-adenine lesions in DNA duplexes: stereochemistry, damage site, and structure. Biochemistry 46(1):182-91 (2007).",
"Ding S, Shapiro R, Geacintov NE, Broyde S. "],

["",
"Increased flexibility enhances misincorporation: temperature effects on nucleotide incorporation opposite a bulky carcinogen-DNA adduct by a Y-family DNA polymerase. J Biol Chem. 282(2):1397-408 (2007).",
"Perlow-Poehnelt RA, Likhterov I, Wang L, Scicchitano DA, Geacintov NE, Broyde S. "],

["",
"The human DNA repair factor XPC-HR23B distinguishes stereoisomeric benzo[a]pyrenyl-DNA lesions. EMBO J. 26(12): 2923-32  (2007).",
"Mocquet V, Kropachev K, Kolbanovskiy M, Kolbanovskiy A, Tapias A, Cai Y, Broyde S, Geacintov NE, Egly JM."],

["",
"Sequence Context- and Temperature-Dependent Nucleotide Excision Repair of a Benzo[a]pyrene Diol Epoxide- Guanine DNA Adduct Catalyzed by Thermophilic UvrABC Proteins. Biochemistry. 46(23), 7006-15(2007).",
"Ruan Q, Liu T, Kolbanovskiy A, Liu Y, Ren J, Skorvaga M, Zou Y, Lader J, Malkani B, Amin S, Houten BV, Geacintov N E. "],

["",
"Injection to Chemical Product Formation and Strand Cleavage. J. Am. Chem. Soc. 129(30):9321-32 (2007).",
"Yun, B.H., Lee, Y.-A, Kim, S.K., Kuzmin, V., Kolbanovskiy, A., Dedon, P.C., Geacintov, N.E., and Shafirovich, S.Hole "],

["",
"Dynamics of a benzo[a]pyrene-derived guanine DNA lesion in TGT and CGC sequence contexts: enhanced mobility in TGT explains conformational heterogeneity, flexible bending, and greater susceptibility to nucleotide excision repair. J Mol Biol. 374(2):292-305 (2007).",
"Cai Y, Patel DJ, Geacintov NE, Broyde S. "],

["",
"Following an environmental carcinogen N2-dG adduct through replication: elucidating blockage and bypass in a high-fidelity DNA polymerase. Nucleic Acids Res. 35(13):4275-88 (2007).",
"Xu P, Oum L, Beese LS, Geacintov NE, Broyde S."]
]
var year2009 =[
["",
"Differential nucleotide excision repair susceptibility of bulky DNA  adducts in  different sequence contexts: hierarchies of recognition signals.  J Mol Biol.  385(1): 30-44 (2009).   PMID: 18948114.",
"Cai Y, Patel DJ, Geacintov NE, Broyde S.  "],

["",
"The Sequence Dependence of Human Nucleotide Excision Repair Efficiencies of  Benzo[a]pyrene-derived DNA Lesions: Insights into the Structural Factors that  favor Dual Incisions. J Mol Biol.  386(5):1193-203  (2009).  PMID: 19162041",
"Kropachev K, Kolbanovskii M, Cai Y, Rodríguez F, Kolbanovskii A, Liu Y, Zhang  L, Amin S, Patel D, Broyde S, Geacintov NE."],

["",
"Absolute Configurations  of Spiroiminodihydantoin and Allantoin Stereoisomers: Comparison of Computed and Measured Electronic Circular  Dichroism Spectra. Chem Res Toxicol. 22(6): 1189-93 (2009).   PubMed PMID:19485408.",
"Ding S, Jia L, Durandin A, Crean C, Kolbanovskiy A, Shafirovich V, Broyde S,  Geacintov NE. "],

["",
"Impact of  Conformational Heterogeneity  OxoG Lesions and Their Pairing Partners on Bypass  Fidelity by Y Family Polymerases. Structure.  17(5):725-36 (2009).  PMID: 19446528.",
"Rechkoblit O, Malinina L, Cheng Y, Geacintov NE, Broyde S, Patel DJ."],

["",
"Development of a Liquid Chromatography Electrospray Ionization Tandem Mass Spectrometry Method for Analysis of Stable 4-Hydroxyequilenin-DNA Adducts in  Human Breast Cancer Cells. Chem Res Toxicol.  22(6):1129-36 ( 2009).  PMID: 19368368.",
"Wang Z, Edirisinghe P, Sohn J, Qin Z, Geacintov NE, Thatcher GR, Bolton JL."],

["",
"Visualizing sequence-governed  nucleotide selectivities and visualizing sequence-governed  nucleotide selectivities and mutagenic consequences through a replicative cycle:  processing of a bulky carcinogen N(2)-dG lesion in a Y-family DNA polymerase. Biochemistry. 2009 Jun 9;48(22):4677-90. PubMed PMID: 19364137.",
"Xu P, Oum L, Lee YC, Geacintov NE, Broyde S. "],

["",
"NMR and computational studies of stereoisomeric equine estrogen-derived DNA cytidine adducts in oligonucleotide duplexes: opposite orientations of diastereomeric forms. Biochemistry. 2009, 48 (30): 7098-109. NIHMS126110.",
"Zhang N, Ding S, Kolbanovskiy A, Shastry A, Kuzmin VA, Bolton JL, Patel DJ,  Broyde S, Geacintov N E."],

["",
"DNA polymerase Zeta cooperates with polymerase Kappa and Iota in translesion DNA synthesis across pyrimidine photodimers in cells from XPV patients. Proc Natl Acad Sci USA  (2009) 106(28):11552-7. PMC2710681.",
"Ziv O, Geacintov NE, Nakajima S, Yasui A, and Livneh Z."],

["https://www.ncbi.nlm.nih.gov/pubmed/19937959?itool=EntrezSystem2.PEntrez.Pubmed.Pubmed_ResultsPanel.Pubmed_RVDocSum&ordinalpos=1",
"Absolute configurations of DNA lesions determined by comparisons of experimental ECD and ORD spectra with DFT calculations.  Chirality 2009, 21(S1):S231-S241. [Epub ahead of print]  PMID: 19937959.",
"Ding S, Kolbanovskiy A, Durandin A, Crean C, Shafirovich V, Broyde S, Geacintov NE."],

["https://www.ncbi.nlm.nih.gov/pubmed/19746460?itool=EntrezSystem2.PEntrez.Pubmed.Pubmed_ResultsPanel.Pubmed_RVDocSum&ordinalpos=2",
"The role of one-electron reduction of lipid hydroperoxides in causing DNA damage.  Chemistry. 2009 Oct 12;15(40):10634-40. PMID:19746460.",
"Crean C, Shao J, Yun BH, Geacintov NE, Shafirovich V."],

["https://www.ncbi.nlm.nih.gov/pubmed/19681599?itool=EntrezSystem2.PEntrez.Pubmed.Pubmed_ResultsPanel.Pubmed_RVDocSum&ordinalpos=4",
"Exploring damage recognition models in prokaryotic nucleotide excision repair with a benzo[a]pyrene-derived lesion in UvrB. Biochemistry. 2009 Sep 29;48(38):8948-57. PMID: 19681599.",
"Jia L, Kropachev K, Ding S, Van Houten B, Geacintov NE, Broyde S."],

["",
"Two-polymerase mechanisms dictate error-free and error-prone translesion DNA synthesis in mammals. EMBO J.  2009, 28(4):383-93. Erratum in: EMBO J. 2009, 28(7):992. PubMed PMID: 19153606.",
"Shachar S, Ziv O, Avkin S, Adar S, Wittschieben J, Reissner T, Chaney S, Friedberg EC, Wang Z, Carell T, Geacintov N, Livneh Z. "],

["",
"Repair of gaps opposite lesions by homologous recombination in mammalian cells. Nucleic Acids Res. 2009, 37(17):5737-48.  PubMed PMID: 19654238.",
"Adar S, Izhar L, Hendel A, Geacintov N, Livneh Z."],

["",
"Structures, metal ion affinities, and fluorescence properties of soluble derivatives of tris((6-phenyl-2-pyridyl)methyl)amine. Inorg Chem. 2009, 48(23):11196-208. PubMed PMID: 19877674.",
"Liang J, Zhang J, Zhu L, Duarandin A, Young VG, Geacintov N, Canary JW. "],

]

var year2010 = [
    ["",
  "Mechanism of error-free and semitargeted mutagenic bypass of an aromatic amine  lesion by Y-family polymerase Dpo4. Nature Struct Mol Biol. 2010 (3):379-88.  PubMed PMID: 20154704.",
 "Rechkoblit O, Kolbanovskiy A, Malinina L, Geacintov NE, Broyde S, Patel DJ. "],

    ["",
  "[a]pyrene diol epoxide stimulates an inflammatory response in normal human lung fibroblasts through a p53 and JNK mediated pathway. Carcinogenesis. 2010 (6):1149-57. PMID: 20382639.",
    "Dreij K, Rhrissorrakrai K, Gunsalus KC, Geacintov NE, Scicchitano DA.  Benzo"],

    ["",
  "Oxidative modification of guanine bases initiated by oxyl radicals derived from photolysis of azo compounds. J Phys Chem B. 2010, 114(19):6685-92. PMID: 20415485.",
    "Shao J, Geacintov NE, Shafirovich V."],

    ["",
  "One-electron oxidation of a pyrenyl photosensitizer covalently attached to DNA and competition between its further oxidation and DNA hole injection. Photochem Photobiol. 2010  ;86(3):563-70. PMID: 20408978.",
    "Yun BH, Dedon PC, Geacintov NE, Shafirovich V. "],

    ["",
    "Oxidation of  8-oxo-7,8-dihydro-2'-deoxyguanosine by oxyl radicals produced by photolysis of  azo compounds. Chem Res Toxicol. 2010, 17;23(5):933-8. PMID: 20408566.",
    "Shao J, Geacintov NE, Shafirovich V."],

    ["",
    "Distant neighbor base sequence context effects in human nucleotide excision repair of a benzo[a]pyrene-derived DNA lesion. J Mol Biol. 2010, 399(3):397-409.  PMID: 20399214.",
    "Cai Y, Kropachev K, Xu R, Tang Y, Kolbanovskii M, Kolbanovskii A, Amin S, Patel DJ, Broyde S, Geacintov NE. ",
    ],

    ["http://www.ncbi.nlm.nih.gov/pubmed/21090780",
     "Base Flipping Free  Energy Profiles for Damaged and Undamaged DNA. Chem  Res Toxicol23, 1868–1870 PMID: 21090780",
       "Zheng H, Cai Y, Ding S, Tang Y, Kropachev K, Zhou Y, Wang L, Wang S, Geacintov NE, Zhang Y, Broyde S.  "],

    ["http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?db=pubmed&amp;cmd=Retrieve&amp;dopt=AbstractPlus&amp;list_uids=18931375&amp;itool=pubmed_DocSum",
  "A bulky DNA lesion derived from a highly potent polycyclic aromatic tumorogen stabilizes nucleosome core particle  structure.Biochemistry 2010, 49(46):9943-5. PMID:  20964331.",
    "Cai Y, Wang L, Ding S, Schwaid A, Geacintov NE, Broyde  S."],

    ["http://www.ncbi.nlm.nih.gov/pubmed/20871811",
  "Base sequence context effects on nucleotide excision repair. J Nucleic  Acids.2010.  PMID: 20871811",
    "Cai Y, Patel DJ, Broyde S, Geacintov NE."],

    ["",
  "Jia L, Geacintov NE, Broyde S.",
  "The N-clasp of human DNA polymerase kappa promotes blockage or error-free  bypass of   adenine- or guanine-benzo[a]pyrenyl lesions. Nucleic Acids Res. 36(20):6571-84 (2008). PMID: 18931375"],
    ["",

  " DNA  sequence context as a determinant of the equantity and chemistry of guanine  oxidation produced by hydroxyl radicals and one-electron produced by hydroxyl  radicals and one-electron oxidants.   J Biol Chem. 283(51):35569-78 (2008).  PMID: 18948263.",
    "Margolin Y, Shafirovich V,  Geacintov NE, DeMott MS, Dedon PC."],
]
var year2011 = [
  ["",
  "Resistance of bulky DNA lesions to nucleotide excision repair can result from extensive aromatic lesion-base stacking interactions.  Nucleic Acids Res. 2011, 39(20): 8752-64",
  "Reeves DA, Mu H, Kropachev K, Cai Y, Ding S, Kolbanovskiy A, Kolbanovskiy M, Chen Y, Krzeminski J, Amin S, Patel DJ, Broyde S, Geacintov NE. "
  ],
  
  ["http://www.ncbi.nlm.nih.gov/pubmed/21741328",
  "Probing for DNA damage with β-hairpins: Similarities in  incision efficiencies of bulky DNA adducts by prokaryotic and human nucleotide  excision repair systems in vitro.</a> <em>DNA  Repair (Amst), 2011, 10(7):684-96.  PMID:  21741328.",
  "Liu Y, Reeves D,  Kropachev K, Cai Y, Ding S, Kolbanovskiy M, Kolbanovskiy A, Bolton JL, Broyde  S, Van Houten B, Geacintov NE."
  ],

  ["http://www.ncbi.nlm.nih.gov/pubmed/20964331",
  "A bulky DNA lesion derived from a  highly potent polycyclic aromatic tumorigen stabilizes nucleosome core particle  structure. Biochemistry, 2011, 23;49(46):9943-5.   PMID:20964331.",
  "Cai Y, Wang L,  Ding S, Schwaid A, Geacintov NE,  Broyde S."
  ],

  ["http://www.ncbi.nlm.nih.gov/pubmed/21361377",
  "Intercalative conformations of the 14R (+)- and 14S  (-)-trans-anti-DB[a,l]P-N⁶-dA adducts: molecular modeling and MD simulations.Chem  Res Toxicol. 2011, 24(4):522-31.   PMID: 21361377.",
  "Cai Y, Ding S, Geacintov NE, Broyde S."
  ],
  
  ["http://www.ncbi.nlm.nih.gov/pubmed/21114286",
  "Inefficient nucleotide excision repair in human cell  extracts of the N-(deoxyguanosin-8-yl)-6-aminochrysene and  5-(deoxyguanosin-N(2)-yl)-6-aminochrysene adducts derived from 6-nitrochrysene.Chem Res Toxicol 2011, 24(1):65-72.  PMID: 21114286.",
  "Krzeminski J,  Kropachev K, Kolbanovskiy M, Reeves D, Kolbanovskiy A, Yun BH, Geacintov NE, Amin S, El-Bayoumy K."
  ],
  
  ["http://www.ncbi.nlm.nih.gov/pubmed/21656632",
  "Solvent Exposure Associated with  Single Abasic Sites Alters the Base Sequence Dependence of Oxidation of Guanine  in DNA in GG Sequence Contexts.ChemBiochem 2011, 12(11):1731-9. PMID:21656632.",
  "Lee YA, Liu Z,  Dedon PC, Geacintov NE,  Shafirovich V."
  ],

  ["",
  "Generation of guanine-thymidine  cross-links in DNA by peroxynitrite/ carbon dioxide. Chem Res Toxicol. 2011, 24(7):1144-52",
  "Yun BH, Geacintov NE, Shafirovich V."
  ],

  ["",
  "PCNA ubiquitination is  important, but not essential for translesion DNA synthesis in mammalian  cells. PLoS Genet. 2011 Sep; 7(9):e1002262.",
  "Hendel A, Krijger PH, Diamant N, Goren Z, Langerak P, Kim J, Reissner T,  Lee KY, Geacintov NE, Carell T, Myung K, Tateishi S, D'Andrea A, Jacobs H,  Livneh Z."
  ]
]

var year2012 = [
  ["",
  "Sequence-dependent variation in the reactivity of 8-oxo-7,8-dihydro-2’-deoxygaunosine toward oxidation.  Chem Res Toxicol. 2012 Feb 20;25(2):366-73.",
  "Lim KS, Taghizadeh K, Wishnok JS, Babu IR, Shafirovich V, Geacintov NE, Dedon PC."
  ],

["",
  "Nuclear Magnetic Resonance Solution Structure of an N(2)-Guanine DNA Adduct Derived from the Potent TumorigenDibenzo[a,l]pyrene: Intercalation from the Minor Groove with Ruptured Watson-Crick Base Pairing. Biochemistry. 2012, 51(48):9751-62. PubMed PMID: 23121427",
  "Tang Y, Liu Z, Ding S, Lin CH, Cai Y, Rodriguez FA, Sayer JM, Jerina DM, Amin S, Broyde S, Geacintov NE."
  ],      

["",
  "Nucleotide excision repair of 2-acetylaminofluorene- and 2-aminofluorene-(C8)-guanine adducts: molecular dynamics simulations elucidate how lesion structure and base sequence context impact repair efficiencies. Nucleic Acids Res. 2012, 40(19):9675-90. PMID: 22904073; PMCID: PMC3479214.",
  "Mu H, Kropachev K, Wang L, Zhang L, Kolbanovskiy A, Kolbanovskiy M, Geacintov NE, Broyde S "
  ],      

["",
  "Preferred WMSA catalytic mechanism of the nucleotidyl transfer reaction in human DNA polymerase κ elucidates error-free bypass of a bulky DNA lesion. Nucleic Acids Res. 2012 Oct;40(18):9193-205. PMID: 22772988; PMCID: PMC3467051.",
  "Lior-Hoffmann L, Wang L, Wang S, Geacintov NE, Broyde S, Zhang Y. "
  ],
  
["",
  "Proton-coupled hole hopping in nucleosomal and free DNA initiated by site-specific hole injection. PhysChemChem Phys. 2012, 14(20):7400-10. PMID: 22526555.",
  "Liu Y, Liu Z, Geacintov NE, Shafirovich V. "
  ],  

["",
  "Lifetimes and reaction pathways of guanine radicalcations and neutral guanine radicals in an oligonucleotide in aqueous solutions. J Am Chem Soc. 2012, 134(10):4955-62. PMID: 22329445; PMCID:PMC3303975..  Nucleic Acids Res. 2011, 39(20): 8752-64",
  "Rokhlenko Y, Geacintov NE, Shafirovich V. "
  ],  

  ["",
  "OI. Human DNA polymerase λ catalyzes lesion bypass across benzo[a]pyrene-derived DNA adduct during base excision repair. DNA Repair (Amst). 2012, 11(4):367-73. PubMed PMID: 22317757.",
  "Skosareva LV, Lebedeva NA, Rechkunova NI, Kolbanovskiy A, Geacintov NE, Lavrik. "
  ],  

  ["",
  "Nucleotide excision repair efficiencies of bulky carcinogen-DNA adducts are governed by a balance between stabilizing and destabilizing interactions. Biochemistry. 2012, 51(7):1486-99. PMID: 22242833; PMCID: PMC3292408.",
  "Cai Y, Geacintov NE, Broyde S. "
  ],

  ["",
  "Structural, energetic and dynamic properties of guanine(C8)-thymine(N3) cross-links in DNA provide insights on susceptibility to nucleotide excision repair. Nucleic Acids Res. 2012, 40(6):2506-17. PMID: 22135299; PMCID: PMC3315297.",
  "Ding S, Kropachev K, Cai Y, Kolbanovskiy M, Durandina SA, Liu Z, Shafirovich V, Broyde S, Geacintov NE."
  ],    

]

var year2013 = [
  ["",
  "One-electron oxidation reactions of purine and pyrimidine bases in cellular DNA. Int J Radiat Biol. 2013 Dec 26. [Epub ahead of print]",
  "Cadet J, Wagner JR, Shafirovich V, Geacintov NE."
  ],    

  ["",
  "Adenine-DNA adduct derived from the nitroreduction of 6-nitrochrysene is more resistant to nucleotide excision repair than guanine-DNA adducts. Chem Res Toxicol. 26(11):1746-54.",
  "Krzeminski J, Kropachev K, Reeves D, Kolbanovskiy A, Kolbanovskiy M, Chen KM, Sharma AK,Geacintov N, Amin S, El-Bayoumy K."
  ],    

  ["",
  "Role of structural and energetic factors in regulating repair of a bulky DNA lesion with different opposite partner bases. Biochemistry 52(33):5517-21.",
  "Mu H, Kropachev K, Chen Y, Zhang H, Cai Y, Geacintov NE, Broyde S."
  ],    

  ["",
  "Free energy profiles of base flipping in intercalative polycyclic aromatic hydrocarbon-damaged DNA duplexes: energetic and structural relationships to nucleotide excision repair susceptibility. Chem Res Toxicol. 26(7):1115-25.",
  "Cai Y, Zheng H, Ding S, Kropachev K, Schwaid AG, Tang Y, Mu H, Wang S, Geacintov NE, Zhang Y, Broyde S."
  ],    

  ["",
  "Generation of Guanine-thymine cross-links in human cells by one-electron oxidation mechanisms. Chem Res Toxicol. 26(7):1031-3.",
  "Madugundu GS, Wagner JR, Cadet J, Kropachev K, Yun BH, Geacintov NE, Shafirovich V."
  ],

  ["",
  "Adenine-DNA adducts derived from the highly tumorigenic Dibenzo[a,l]pyrene are resistant to nucleotide excision repair while guanine adducts are not. Chem Res Toxicol. 20: 26(5):783-93.",
  "Kropachev K, Kolbanovskiy M, Liu Z, Cai Y, Zhang L, Schwaid AG, Kolbanovskiy A, Ding S, Amin S, Broyde S, Geacintov NE. "
  ],

  ["",
  "Thermodynamic profiles and nuclear magnetic resonance studies of oligonucleotide duplexes containing single diastereomericspiroiminodihydantoin lesions. Biochemistry 26:52(8):1354-63.",
  "Khutsishvili I, Zhang N, Marky LA, Crean C, Patel DJ, Geacintov NE, Shafirovich V."
  ],

  ["",
  "Genomic assay reveals tolerance of DNA damage by both translesion DNA synthesis and homology-dependent repair in mammalian cells. ProcNatlAcadSci U S A. 16: 110(16):E1462-9",
  "Izhar L, Ziv O, Cohen IS, Geacintov NE, Livneh Z. "
  ],
]

var year2014 = [
  ["https://www.ncbi.nlm.nih.gov/pubmed/25148552",
  "Structural and dynamic characterization of polymerase κ's minor groove lesion processing reveals how adduct topology impacts fidelity.Biochemistry,  2014, 53:5683-91.  PMID:",
  "Lior-Hoffmann L, Ding S, Geacintov NE, Zhang Y, Broyde S."
  ],

  ["",
  "Identification of novel DNA-damage tolerance genes reveals regulationoftranslesion DNA synthesis by nucleophosmin. Nature Communications. 2014, 5:5437.",
  "Ziv O, Zeisel A, Mirlas-Neisberg N, Swain U, Nevo R, Ben-Chetrit N, MartelliMP, Rossi R, Schiesser S, Canman CE, Carell T, Geacintov NE, Falini B, Domany E, Livneh Z."
  ],

  ["",
  "(Generation of guanine-amino acidcross-links by a free radical combination mechanism. PhysChemChem Phys. 2014,16(23):11729-36.",
  "Uvaydov Y, Geacintov NE, Shafirovich V."
  ],

  ["",
  "The relationships between XPC binding to conformationally diverse DNA adducts andtheir excision by the human NER system: is there a correlation? DNA Repair(Amst). 2014, 19:55-63.",
  "Lee YC, Cai Y, Mu H, Broyde S, Amin S, Chen X, Min JH, Geacintov NE."
  ],

  ["",
  "Mechanistic aspects of hydration of guanine radical cations in DNA. J Am Chem Soc. 2014,136(16):5956-62.",
  "Rokhlenko Y, Cadet J, Geacintov NE, Shafirovich V."
  ],

  ["",
  "Nuclear magnetic resonance studies of anN2-guanine adduct derived from the tumorigendibenzo[a,l]pyrene in DNA: impact ofadduct stereochemistry, size, and local DNA sequence on solution conformations.Biochemistry. 2014, 53(11):1827-41.",
  "Rodríguez FA, Liu Z, Lin CH, Ding S, Cai Y, Kolbanovskiy A, Kolbanovskiy M, Amin S, Broyde S, Geacintov NE."
  ],

  ["",
  "Structural basis for therecognition of diastereomeric 5',8-cyclo-2'-deoxypurine lesions by the humannucleotide excision repair system. Nucleic Acids Res. 2014, 42(8):5020-32.",
  "Kropachev K, Ding S, Terzidis MA, Masi A, Liu Z, Cai Y, Kolbanovskiy M,Chatgilialoglu C, Broyde S, Geacintov NE, Shafirovich V. "
  ],

  ["",
  "One-electron oxidationreactions of purine and pyrimidine bases in cellular DNA. Int J Radiat Biol. 2014, 90(6):423-32.",
  "Cadet J, Wagner JR, Shafirovich V, Geacintov NE. "
  ],

  ["",
  "Ribonucleotides as nucleotide excision repairsubstrates. DNA Repair (Amst). 2014 Jan;13:55-60.  PMID: 24290807.",
  "Cai Y, Geacintov NE, Broyde S."
  ],

  ["https://www.ncbi.nlm.nih.gov/pubmed/25460917",
  ".Human DNA polymerases catalyze lesion bypass across benzo[a]pyrene-derived DNA adduct clustered with an abasic site.  DNA Repair (Amst). 2014 Dec;24:1-9.  PMID: 25460917",
  "Starostenko LV, Rechkunova NI, Lebedeva NA, Kolbanovskiy A, Geacintov NE, LavrikOI."
  ],
]

var year2015 = [
  ["",
  "Correction:Resistance to Nucleotide Excision Repair of Bulky Guanine Adducts Opposite Abasic  Sites in DNA Duplexes and Relationships between Structure and Function. PLoS One.  2015 Oct 29;10(10):e0142068. PMCID: PMC4626036. Erratum in: PLoS One. 2015;10(10):e0142068. Lei, Jia [corrected to Jia, Lei]. PMCID: PMC4560436.",
  "Liu Z, Ding S, Kropachev K, Jia L, Amin S, Broyde S, Geacintov NE."
  ],

  ["",
  "DNA sequence  context greatly affects the accuracy of bypass across an ultraviolet light 6-4 photoproduct in mammalian cells. Mutat Res. 2015 Oct;780:71-6. PMCID: PMC4871125.",
  "Shriber P, Leitner-Dagan Y, Geacintov N, Paz-Elizur T, Livneh Z. "
  ],

  ["",
  "Recognition of Damaged DNA for Nucleotide Excision Repair: A Correlated Motion Mechanism with a Mismatched cis-syn Thymine Dimer Lesion. Biochemistry. 2015 Sep 1;54(34):5263-7.  PMCID: PMC4748833.",
  "Mu H, Geacintov NE, Zhang Y, Broyde S."
  ],

  ["",
  "Differences in the Access of Lesions to the Nucleotide Excision Repair Machinery in Nucleosomes. Biochemistry. 2015 July 14;54(27):4181-5. PMCID: PMC4862310.",
  "Cai Y, Kropachev K, Terzidis MA, Masi A, Chatgilialoglu C, Shafirovich V, Geacintov NE, Broyde S."
  ],

  ["",
  "Oxidatively Generated Guanine(C8)-Thymine(N3) Intrastrand Cross-links in Double-stranded DNA Are Repaired by Base Excision Repair Pathways. J Biol Chem. 2015 June 5;290(23):14610-7. PMCID: PMC4505527.",
  "Talhaoui I, Shafirovich V, Liu Z, Saint-Pierre C, Akishev Z, Matkarimov BT, Gasparutto D, Geacintov NE, Saparbaev M. "
  ],

  ["",
  "DNA lesion identity drives choice of damage tolerance pathway in murine cell chromosomes. Nucleic Acids Res. 2015 Feb 18;43(3):1637-45. PMCID: PMC4330363",
  "Cohen IS, Bar C, Paz-Elizur T, Ainbinder E, Leopold K, de Wind N, Geacintov, N, Livneh Z."
  ],

]

var year2016 = [
  ["",
  "Translesion synthesis past guanine(C8)-thymine(N3) intrastrand cross-links catalyzed by selected A- and Y-family polymerases. MolBiosyst. 2016 May 24;12(6):1892-900. PMCID: PMC4879090.",
  "Lee YA, Lee YC, Geacintov NE, Shafirovich V. "
  ],

  ["",
  "Characterization of the interactions of PARP-1 with UV-damaged DNA in vivo and in vitro. Sci Rep. 2016  Jan 12;6:19020. PMCID: PMC4709520.",
  "Purohit NK, Robu M, Shah RG, Geacintov NE, Shah GM."
  ],

  ["",
  "Base and Nucleotide Excision  Repair of Oxidatively Generated Guanine Lesions in DNA. J Biol Chem. 2016 Mar  4;291(10):5309-19. PMCID: PMC4777862.",
  "Shafirovich V, Kropachev K, Anderson T, Liu Z, Kolbanovskiy M, Martin BD,  Sugden K, Shim Y, Chen X, Min JH, Geacintov NE"
  ],

  ["",
  "Entrapment of a Histone Tail by  DNA Lesion in a Nucleosome Suggests the Lesion Impacts Epigenetic Marking: A Molecular Dynamics Study. Biochemistry. 2016 Jan 19;55(2):239-42. PMCID: PMC4721520.",
  "Fu I, Cai Y, Zhang Y, Geacintov NE, Broyde S."
  ],

  ["",
  "Nucleotide Excision Repair andTranscription-coupled DNA Repair Abrogate the Impact of DNA Damage onTranscription. J Biol Chem. 2016 Jan 8;291(2):848-61. PMCID: PMC4705403",
  "Nadkarni A, Burns JA, Gandolfi A, Chowdhury MA, Cartularo L, Berens C,Geacintov NE, Scicchitano DA."
  ],
]



var Publications = React.createClass({
  getInitialState: function() {
    return {year: 2016
    };
  },
  handleYearChange: function(e) {
    this.setState({year:e.target.value});
  },

  handleData: function() {
    var list = [""];
    if(this.state.year == 2016)
      list = year2016;
    if(this.state.year == 2015)
    list = year2015;
    if(this.state.year == 2014)
      list = year2014;
    if(this.state.year == 2013)
      list = year2013;
    if(this.state.year == 2012)
      list = year2012;
    if(this.state.year == 2011)
      list = year2011;
    if(this.state.year == 2010)
      list = year2010;
    if(this.state.year == 2009)
      list = year2009;
    if(this.state.year == 2008)
      list = year2008;


    var authorStyle = {
      fontSize:"13px",
      fontFamily:"'Roboto'",
      color:"grey",
      padding:"10px",
    }
    return(
          list.map(function(listValue){ 
            if(listValue[0] == "")
              return (
                  <a key = {listValue[1]} className="list-group-item" style = {{fontSize:"15px"}}> {listValue[1]} <span style = {authorStyle}> {listValue[2]}</span> </a>
              )
            else
              return (
                  <a key = {listValue[1]} className="list-group-item" href = {listValue[0]} style = {{fontSize:"15px",fontWeight:"bold"}}> {listValue[1]} <span style = {authorStyle}> {listValue[2]}</span> </a>
                )
          })
      )
  }

  ,
  render: function() {
    let radiocontainer = {

    }
    return (
        <div>


              <div style = {radiocontainer}>
                <p>Current Year: {this.state.year}</p>
                <div className="form-check form-check-inline"><label className="form-check-label">
                  <input className="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" 
                    value={2016} 
                    onClick= {this.handleYearChange}
                    /> 
                    <h6>2016</h6>
                </label></div>
                
                <div className="form-check form-check-inline"><label className="form-check-label">
                  <input className="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" 
                    value={2015} 
                    onClick= {this.handleYearChange}
                    /> 
                    <h6>2015</h6>
                </label></div>
                
                <div className="form-check form-check-inline"><label className="form-check-label">
                  <input className="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" 
                    value={2014} 
                    onClick= {this.handleYearChange}
                    /> 
                    <h6>2014</h6>
                </label></div>
                
                <div className="form-check form-check-inline"><label className="form-check-label">
                  <input className="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" 
                    value={2013} 
                    onClick= {this.handleYearChange}
                    /> 
                    <h6>2013</h6>
                </label></div>
                
                <div className="form-check form-check-inline"><label className="form-check-label">
                  <input className="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" 
                    value={2012} 
                    onClick= {this.handleYearChange}
                    /> 
                    <h6>2012</h6>
                </label></div>
                
                <div className="form-check form-check-inline"><label className="form-check-label">
                  <input className="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" 
                    value={2011} 
                    onClick= {this.handleYearChange}
                    /> 
                    <h6>2011</h6>
                </label></div>
                
                <div className="form-check form-check-inline"><label className="form-check-label">
                  <input className="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" 
                    value={2010} 
                    onClick= {this.handleYearChange}
                    /> 
                    <h6>2010</h6>
                </label></div>
                
                <div className="form-check form-check-inline"><label className="form-check-label">
                  <input className="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" 
                    value={2009} 
                    onClick= {this.handleYearChange}
                    /> 
                    <h6>2009</h6>
                </label></div>
                <div className="form-check form-check-inline"><label className="form-check-label">
                  <input className="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" 
                    value={2008} 
                    onClick= {this.handleYearChange}
                    /> 
                    <h6>2008-2006</h6>
                </label></div>
              </div>

               {this.handleData()}

         </div>
    );
  }
});

ReactDOM.render(<Publications/>,document.getElementById('publicationReactJS'));
